spring:
  datasource:
    admin:
      jdbc-url: jdbc:postgresql://localhost:5433/fitness_tracker_database
      driver-class-name: org.postgresql.Driver
      username: admin
      password: qwerty2
    user:
      jdbc-url: jdbc:postgresql://localhost:5433/fitness_tracker_database
      driver-class-name: org.postgresql.Driver
      username: user
      password: qwerty1
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect